# Generated by Django 5.0 on 2024-03-09 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0008_contactdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='body',
            new_name='msg',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='satisfy',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
