# Generated by Django 5.0 on 2024-03-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0009_rename_body_feedback_msg_remove_feedback_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='msg',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='satisfy',
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
